# Site settings
title:       Protractor Ninja!
email:       austin@angerson.org
author:      Austin Anderson
description: "I'm not as angry as you might expect."
baseurl:     ""
url:         ""

# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
show_social_icons: true
github_username: ProtractorNinja
stackoverflow_id: 2259675/protractor-ninja
twitter_username: ProtractorNinja
google_plus_id:
linkedin_username: protractorninja
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     3
sass:
  compressed: true
